# Generated by Django 3.2.4 on 2021-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(max_length=200),
        ),
    ]
