# Generated by Django 3.2.5 on 2021-07-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_origin_stop', models.CharField(max_length=200)),
                ('users_dest_stop', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dublinbusapplication.user')),
            ],
        ),
    ]
