# Generated by Django 3.2.5 on 2021-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance_planned', models.FloatField(default=0)),
                ('total_trips_planned', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
