# Generated by Django 3.2.4 on 2021-08-04 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dublinbusapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteJourney',
            fields=[
                ('users_origin_stop', models.CharField(max_length=200)),
                ('users_dest_stop', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
