# Generated by Django 3.2.5 on 2021-08-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapplication', '0002_useraccountmetrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
