# Generated by Django 3.2.4 on 2021-07-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapplication', '0003_bikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='bikes',
            old_name='lat',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='bikes',
            old_name='lng',
            new_name='Longitude',
        ),
        migrations.RenameField(
            model_name='bikes',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='bikes',
            old_name='number',
            new_name='Number',
        ),
    ]
