# USER = "CiansDB"
# PASSWORD = "DBG18_2021"
# PORT = "3306"
# DB = "dublinbus"
# URI = "dublinbus.cmxnicqe342l.eu-west-1.rds.amazonaws.com"

USER = "team18"
PASSWORD = "Q{#9{aG.c7P^HBeQ"
PORT = "3306"
DB = "team18"
URI = "telemachus.ucd.ie"
